// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcqKazfjWXQUEVlQBAb0WeWuXc3ywVGcE',
    appId: '1:295257017311:web:3bbc51697e3312f224926a',
    messagingSenderId: '295257017311',
    projectId: 'rentapp-7a3ec',
    authDomain: 'rentapp-7a3ec.firebaseapp.com',
    storageBucket: 'rentapp-7a3ec.appspot.com',
    measurementId: 'G-PBS2457X32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3L-1cami7weVTtJG_FYjrxYtGNTlXqoE',
    appId: '1:295257017311:android:1493c7114d0e3bbf24926a',
    messagingSenderId: '295257017311',
    projectId: 'rentapp-7a3ec',
    storageBucket: 'rentapp-7a3ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCucDc_LcY6whcwsXQlT8nDwI9oVqU_mqk',
    appId: '1:295257017311:ios:c9858759e56a94c124926a',
    messagingSenderId: '295257017311',
    projectId: 'rentapp-7a3ec',
    storageBucket: 'rentapp-7a3ec.appspot.com',
    iosClientId: '295257017311-coej1u0op23flfkh7buhtq2ao5fid6n5.apps.googleusercontent.com',
    iosBundleId: 'com.example.carRent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCucDc_LcY6whcwsXQlT8nDwI9oVqU_mqk',
    appId: '1:295257017311:ios:c9858759e56a94c124926a',
    messagingSenderId: '295257017311',
    projectId: 'rentapp-7a3ec',
    storageBucket: 'rentapp-7a3ec.appspot.com',
    iosClientId: '295257017311-coej1u0op23flfkh7buhtq2ao5fid6n5.apps.googleusercontent.com',
    iosBundleId: 'com.example.carRent',
  );
}
